### PR TITLE
Make db pool size configurable

### PR DESCRIPTION
**Pull request by tej99**
# Motivation and Context

The db connection pool needs to be configurable for performance tweaking. 

# How to test?

1) Spin up the survey service with default settings
2) Hit the service with multiple requests (I used a Jmeter script with 100 users)
3) Watch your db connections go up (I used pgadmin to monitor open connections)
4) Stop the requests to the service and the db connections should go back to approx where they started.
5) Set environment var MAX_IDLE_CONN=50 and re run survey service
6) Repeat steps 2, 3 and 4 but instead of the connections going back to where they started you will see more idle connections than you started with.

# Links

https://trello.com/c/SwXkyTRo/44-optimise-db-connection-settings

### CODE REVIEW

**Comment by tej99** [comment]
[Optimise DB Connection Settings](https://trello.com/c/SwXkyTRo/44-optimise-db-connection-settings)

**Comment by madeye-matt** [comment]
@pricem14pc @davidmort and I confirmed that the source does get uploaded to cf as part of the deployment (but not in the default location). However, there is a further issue: the migrate library we used doesn't support clustered environments (you'd have to stagger the launch to get it to work)

**Comment by benjefferies** [comment]
If this works then we can merge it right?

**Comment by tej99** [comment]
@benjefferies It works locally but due to the problems @madeye-matt mentioned we are not able to test these changes in a cloud foundry environment. @pricem14pc says we can merge it in if it is blocking other things but this will still need testing properly either way.

**Comment by benjefferies** [comment]
Yeah understand the issue with CF but that's the case whether this goes in or not. I think this can be tested functionally locally and then performance test separately. It wouldn't regress performance if all values are set to the same as they were by default

**Pull request merged**
