### PR TITLE
RAS-1238 Update to docker compose from docker-compose

### PR DESCRIPTION
**Pull request by arroyoAle**
# What and why?
Updating references to the now removed `docker-compose` in favour of `docker compose`
# How to test?
Run the `make integration-tests` command, make sure that the `docker-compose.yml` files now work, and make sure that the tests run properly in the GHA build
# Jira
[RAS-1238](https://jira.ons.gov.uk/browse/RAS-1238)

### CODE REVIEW

**Review by anwilkie — COMMENTED** [review]
The PR itself is fine, but you won't be able to merge this in because the signed bot commits aren't set up yet. I went ahead and added the secret variables for this repo, so all that needs to be done now is to amend the GA build to use them.

**Review by matthew-robinson-ons — APPROVED** [review]
get dependencies looks good with the update and make commands work as expected

**Comment by arroyoAle** [comment]
> The PR itself is fine, but you won't be able to merge this in because the signed bot commits aren't set up yet. I went ahead and added the secret variables for this repo, so all that needs to be done now is to amend the GA build to use them.

I've added the GPG signing step in the GHA, thanks for adding the secrets

**Comment by arroyoAle** [comment]
Recreated on https://github.com/ONSdigital/rm-survey-service/pull/158 with bot signing

**Pull request closed without merging**
