### PR TITLE
Change BRES classifiers from RU_REF to FORM_TYPE for 2024

### PR DESCRIPTION
**Pull request by pricem14pc**
# What and why?

BRES 2024 will be using the FORM_TYPE classifier and not RU_REF. This db_migration updates those is the database.

# How to test

Following building your own dev namespace, `/deploy` this PR to your environment and ensure the changes in the `.up` delta 16 are applied. I'm unsure how the automated deployment of the `.down` backout SQL is applied, but you can manually apply the SQL it contains with PgAdmin or psql to see the configuration reverted.

Once delta 16 is applied and the records are updated, create a new BRES collection exercise and ensure you can upload a SURVEY_PERIOD_0001.xlsx SEFT in Rops (i.e. this is a standard form type filename and NOT a 49900000001.xlsx filename as has been the case in previous BRES collection exercises). Progress it through to Go Live and register a respondent, and download the file, then upload a response.

### CODE REVIEW

**Review by anwilkie — APPROVED** [review]

**Review by arroyoAle — CHANGES_REQUESTED** [review]
This works fine but it will fail when deploying to prerpod after the merge as the BRES acceptance test no longer works as it is set up for the RU_REF classifier

**Comment by pricem14pc** [comment]
> This works fine but it will fail when deploying to prerpod after the merge as the BRES acceptance test no longer works as it is set up for the RU_REF classifier

Great spot !!

**Review by arroyoAle — APPROVED** [review]
Happy with the changes to the spinnaker pipeline

**Comment by pricem14pc** [comment]
The Spinnaker fullDeploymentTemplate has been updated prior to this merge

**Pull request merged**
