### PR TITLE
update go to 1.19 and rebuild packages

### PR DESCRIPTION
**Pull request by matthew-robinson-ons**
# What and why?
update go to version 1.19 
# How to test?
run acceptance tests
# Trello
https://trello.com/c/YrEjXWTy/2206-upgrade-rm-survey-service-to-go-119

### CODE REVIEW

**Comment by matthew-robinson-ons** [comment]
[Upgrade rm-survey-service to go 1.19](https://trello.com/c/YrEjXWTy/2206-upgrade-rm-survey-service-to-go-119)

**Review by LJBabbage — APPROVED** [review]
Worked without issue for me

**Review by insacuri — CHANGES_REQUESTED** [review]
You need to upgrade the go version in the github workflows

**Review by insacuri — CHANGES_REQUESTED** [review]
```
survey-65b65b8f9d-4kvkw                                         0/1     CrashLoopBackOff   2 (9s ago)   45s
uaa-54c8988bd4-q2558                                            1/1     Running            0            26m
manna@Adams-MacBook-Pro response-operations-ui % kc logs -f survey-65b65b8f9d-4kvkw
exec /usr/local/bin/main: no such file or directory
```

Doesn't actually work >_<

**Pull request merged**
